### ISSUE TITLE
mkfs.ext4 called without '-F', and is hanging because save.tmp is a file, not a block special device.

### ISSUE THREAD

**Issue by grangerx** [slutzo/saucepan#1]
On a CentOS 7 device, the saucepan.sh line:

`mkfs.ext4 "${save_temp_file}" >& /dev/null`

is silently hanging because it is asking a question but output is redirected to /dev/null:
`
/tmp/WHATEVERNAME_save.tmp is not a block special device.
Proceed anyway? (y,n)
`

Thus, the script hangs until a button is pushed, but unless that button is Y, the save.tmp won't be properly formatted and the resulting ROM won't have access to save-states.

Adding a '-F' parameter forces the mkfs.ext4 to succeed, which works, but might be dangerous without sufficient validation that the tmp file path/name is correct, etc.

**Comment by slutzo** [comment]
Aw, rats. I was hoping I wouldn't have to specify a -F, since my Ubuntu test system just makes the files system without griping.

I'll just add the "-F".  I'm not too worried about it causing any damage, since the way save_temp_file is defined, there's no way it can be an empty string or the root file system or something.

**Comment by slutzo** [comment]
Aw, rats. I was hoping I wouldn't have to specify a -F, since my Ubuntu test system just makes the file system without griping.

I'll just add the "-F". I'm not too worried about it causing any damage, since the way save_temp_file is defined, there's no way it can be an empty string or the root file system or something.
